#!/bin/sh

set -eu # -x for verbose logging to ensemble debug-log

# Get the database settings; if not set, wait for this hook to be
# invoked again
host=`relation-get host`
if [ -z "$database" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

relation_port=`relation-get port`
port=${relation_port:-27017}

[[ -f "$(dirname $0)/config" ]] && source "$(dirname $0)/config" # goes away with config.yaml / config-get
app_name=${config_app_name:-"mynodeapp"} # `config-get app_name`
app_dir=${config_app_dir:-"/opt/${app_name}"} # `config-get app_dir`

ensemble-log "configuring ${app_name} to work with the mongodb service"

config_file_path=$app_dir/config/config.js
if [ -f $config_file_path ]; then
  ensemble-log "Writing $app_name config file $config_file_path"
  sed -i 's/mongo_host.*/mongo_host" : ${host}' $app_config_file
  sed -i 's/mongo_port.*/mongo_port" : ${port}' $app_config_file
fi

ensemble-log "Starting app"
service ${app_name} start

