#!/bin/bash

set -eu 

# Get the database settings; if not set, wait for this hook to be
# invoked again
host=`relation-get hostname`
if [ -z "$host" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

relation_port=`relation-get port`
port=${relation_port:-27017}

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"

configure_app() {
  juju-log "configuring ${app_name} to work with the mongodb service"

  config_file_path=$app_dir/config/config.js
  if [ -f $config_file_path ]; then
    juju-log "Writing $app_name config file $config_file_path"
    sed -i "s/mongo_host.*/mongo_host\" : \"${host}\"/" $config_file_path
    sed -i "s/mongo_port.*/mongo_port\" : ${port}/" $config_file_path
  fi
}
configure_app

juju-log "(re)starting app"
service ${app_name} restart || service ${app_name} start

