#!/bin/bash

[[ -f "$(dirname $0)/config" ]] && source "$(dirname $0)/config" # goes away with config.yaml / config-get
app_name=${config_appname:-"mynodeapp"} # `config-get app_name`

service ${app_name} stop

