#!/bin/sh

[[ -f "$(dirname $0)/config" ]] && source "$(dirname $0)/config" # goes away with config.yaml / config-get
app_port=${config_app_port:-"8000"} # `config-get app_port`

relation-set port=$app_port hostname=`hostname -f`

